// <auto-generated />
using BetPlacer.Scheduler.Worker.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BetPlacer.Scheduler.Worker.Migrations
{
    [DbContext(typeof(SchedulerDbContext))]
    [Migration("20240702192501_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BetPlacer.Scheduler.Worker.Models.Entities.SchedulerModel", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<bool>("AnalysisDone")
                        .HasColumnType("boolean")
                        .HasColumnName("analysis_done");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("date");

                    b.Property<bool>("OddsFilled")
                        .HasColumnType("boolean")
                        .HasColumnName("odds_filled");

                    b.HasKey("Code")
                        .HasName("p_k_scheduler_execution");

                    b.ToTable("scheduler_execution");
                });
#pragma warning restore 612, 618
        }
    }
}
