// <auto-generated />
using System;
using BetPlacer.Fixtures.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BetPlacer.Fixtures.API.Migrations
{
    [DbContext(typeof(FixturesDbContext))]
    [Migration("20240503115338_AddFixtureStats")]
    partial class AddFixtureStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BetPlacer.Fixtures.API.Models.Entities.FixtureGoalsModel", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<int>("FixtureCode")
                        .HasColumnType("integer")
                        .HasColumnName("fixture_code");

                    b.Property<string>("Minute")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("minute");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Code")
                        .HasName("p_k_fixture_goals");

                    b.HasIndex("FixtureCode");

                    b.ToTable("fixture_goals");
                });

            modelBuilder.Entity("BetPlacer.Fixtures.API.Models.Entities.FixtureModel", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<int>("AwayTeamGoals")
                        .HasColumnType("integer")
                        .HasColumnName("away_team_goals");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("away_team_id");

                    b.Property<string>("AwayTeamImage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("away_team_image");

                    b.Property<string>("AwayTeamName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("away_team_name");

                    b.Property<double>("AwayTeamPPG")
                        .HasColumnType("double precision")
                        .HasColumnName("away_team_p_p_g");

                    b.Property<double>("AwayTeamXG")
                        .HasColumnType("double precision")
                        .HasColumnName("away_team_x_g");

                    b.Property<int>("HomeTeamGoals")
                        .HasColumnType("integer")
                        .HasColumnName("home_team_goals");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("home_team_id");

                    b.Property<string>("HomeTeamImage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("home_team_image");

                    b.Property<string>("HomeTeamName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("home_team_name");

                    b.Property<double>("HomeTeamPPG")
                        .HasColumnType("double precision")
                        .HasColumnName("home_team_p_p_g");

                    b.Property<double>("HomeTeamXG")
                        .HasColumnType("double precision")
                        .HasColumnName("home_team_x_g");

                    b.Property<int>("SeasonCode")
                        .HasColumnType("integer")
                        .HasColumnName("season_code");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Code")
                        .HasName("p_k_fixtures");

                    b.ToTable("fixtures");
                });

            modelBuilder.Entity("BetPlacer.Fixtures.API.Models.Entities.Trade.FixtureStatsTradeModel", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<double>("AwayAverageGoalsConcededFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_average_goals_conceded_f_t_total");

                    b.Property<double>("AwayAverageGoalsConcededFTTotalAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_average_goals_conceded_f_t_total_at_away");

                    b.Property<double>("AwayAverageGoalsConcededHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_average_goals_conceded_h_t_total");

                    b.Property<double>("AwayAverageGoalsConcededHTTotalAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_average_goals_conceded_h_t_total_at_away");

                    b.Property<double>("AwayAverageGoalsConcededTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_average_goals_conceded_total");

                    b.Property<double>("AwayAverageGoalsConcededTotalAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_average_goals_conceded_total_at_away");

                    b.Property<double>("AwayAverageGoalsScoredFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_average_goals_scored_f_t_total");

                    b.Property<double>("AwayAverageGoalsScoredFTTotalAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_average_goals_scored_f_t_total_at_away");

                    b.Property<double>("AwayAverageGoalsScoredHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_average_goals_scored_h_t_total");

                    b.Property<double>("AwayAverageGoalsScoredHTTotalAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_average_goals_scored_h_t_total_at_away");

                    b.Property<double>("AwayAverageGoalsScoredTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_average_goals_scored_total");

                    b.Property<double>("AwayAverageGoalsScoredTotalAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_average_goals_scored_total_at_away");

                    b.Property<double>("AwayBothToScorePercentTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_both_to_score_percent_total");

                    b.Property<double>("AwayBothToScorePercentTotalAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_both_to_score_percent_total_at_away");

                    b.Property<double>("AwayDrawsPercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_draws_percent_f_t_total");

                    b.Property<double>("AwayDrawsPercentFTTotalAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_draws_percent_f_t_total_at_away");

                    b.Property<double>("AwayDrawsPercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_draws_percent_h_t_total");

                    b.Property<double>("AwayDrawsPercentHTTotalAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_draws_percent_h_t_total_at_away");

                    b.Property<double>("AwayFailedToScorePercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_failed_to_score_percent_f_t_total");

                    b.Property<double>("AwayFailedToScorePercentFTTotalAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_failed_to_score_percent_f_t_total_at_away");

                    b.Property<double>("AwayFailedToScorePercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_failed_to_score_percent_h_t_total");

                    b.Property<double>("AwayFailedToScorePercentHTTotalAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_failed_to_score_percent_h_t_total_at_away");

                    b.Property<double>("AwayFailedToScorePercentTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_failed_to_score_percent_total");

                    b.Property<double>("AwayFailedToScorePercentTotalAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_failed_to_score_percent_total_at_away");

                    b.Property<double>("AwayFirstToScorePercentTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_first_to_score_percent_total");

                    b.Property<double>("AwayFirstToScorePercentTotalAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_first_to_score_percent_total_at_away");

                    b.Property<double>("AwayFixturesWithoutConcededGoalsPercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_fixtures_without_conceded_goals_percent_f_t_total");

                    b.Property<double>("AwayFixturesWithoutConcededGoalsPercentFTTotalAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_fixtures_without_conceded_goals_percent_f_t_total_at_away");

                    b.Property<double>("AwayFixturesWithoutConcededGoalsPercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_fixtures_without_conceded_goals_percent_h_t_total");

                    b.Property<double>("AwayFixturesWithoutConcededGoalsPercentHTTotalAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_fixtures_without_conceded_goals_percent_h_t_total_at_away");

                    b.Property<double>("AwayFixturesWithoutConcededGoalsPercentTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_fixtures_without_conceded_goals_percent_total");

                    b.Property<double>("AwayFixturesWithoutConcededGoalsPercentTotalAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_fixtures_without_conceded_goals_percent_total_at_away");

                    b.Property<int>("AwayGoalsConcededAt00To15")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at00_to15");

                    b.Property<int>("AwayGoalsConcededAt00To15AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at00_to15_at_away");

                    b.Property<double>("AwayGoalsConcededAt00To15Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at00_to15_percent");

                    b.Property<double>("AwayGoalsConcededAt00To15PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at00_to15_percent_at_away");

                    b.Property<int>("AwayGoalsConcededAt16To30")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at16_to30");

                    b.Property<int>("AwayGoalsConcededAt16To30AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at16_to30_at_away");

                    b.Property<double>("AwayGoalsConcededAt16To30Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at16_to30_percent");

                    b.Property<double>("AwayGoalsConcededAt16To30PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at16_to30_percent_at_away");

                    b.Property<int>("AwayGoalsConcededAt31To45")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at31_to45");

                    b.Property<int>("AwayGoalsConcededAt31To45AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at31_to45_at_away");

                    b.Property<double>("AwayGoalsConcededAt31To45Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at31_to45_percent");

                    b.Property<double>("AwayGoalsConcededAt31To45PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at31_to45_percent_at_away");

                    b.Property<int>("AwayGoalsConcededAt46To60")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at46_to60");

                    b.Property<int>("AwayGoalsConcededAt46To60AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at46_to60_at_away");

                    b.Property<double>("AwayGoalsConcededAt46To60Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at46_to60_percent");

                    b.Property<double>("AwayGoalsConcededAt46To60PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at46_to60_percent_at_away");

                    b.Property<int>("AwayGoalsConcededAt61To75")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at61_to75");

                    b.Property<int>("AwayGoalsConcededAt61To75AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at61_to75_at_away");

                    b.Property<double>("AwayGoalsConcededAt61To75Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at61_to75_percent");

                    b.Property<double>("AwayGoalsConcededAt61To75PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at61_to75_percent_at_away");

                    b.Property<int>("AwayGoalsConcededAt76To90")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at76_to90");

                    b.Property<int>("AwayGoalsConcededAt76To90AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at76_to90_at_away");

                    b.Property<double>("AwayGoalsConcededAt76To90Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at76_to90_percent");

                    b.Property<double>("AwayGoalsConcededAt76To90PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at76_to90_percent_at_away");

                    b.Property<int>("AwayGoalsConcededFTTotal")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_f_t_total");

                    b.Property<int>("AwayGoalsConcededFTTotalAtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_f_t_total_at_away");

                    b.Property<int>("AwayGoalsConcededHTTotal")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_h_t_total");

                    b.Property<int>("AwayGoalsConcededHTTotalAtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_h_t_total_at_away");

                    b.Property<int>("AwayGoalsConcededTotal")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_total");

                    b.Property<int>("AwayGoalsConcededTotalAtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_total_at_away");

                    b.Property<int>("AwayGoalsScoredAt00To15")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at00_to15");

                    b.Property<int>("AwayGoalsScoredAt00To15AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at00_to15_at_away");

                    b.Property<double>("AwayGoalsScoredAt00To15Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at00_to15_percent");

                    b.Property<double>("AwayGoalsScoredAt00To15PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at00_to15_percent_at_away");

                    b.Property<int>("AwayGoalsScoredAt16To30")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at16_to30");

                    b.Property<int>("AwayGoalsScoredAt16To30AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at16_to30_at_away");

                    b.Property<double>("AwayGoalsScoredAt16To30Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at16_to30_percent");

                    b.Property<double>("AwayGoalsScoredAt16To30PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at16_to30_percent_at_away");

                    b.Property<int>("AwayGoalsScoredAt31To45")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at31_to45");

                    b.Property<int>("AwayGoalsScoredAt31To45AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at31_to45_at_away");

                    b.Property<double>("AwayGoalsScoredAt31To45Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at31_to45_percent");

                    b.Property<double>("AwayGoalsScoredAt31To45PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at31_to45_percent_at_away");

                    b.Property<int>("AwayGoalsScoredAt46To60")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at46_to60");

                    b.Property<int>("AwayGoalsScoredAt46To60AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at46_to60_at_away");

                    b.Property<double>("AwayGoalsScoredAt46To60Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at46_to60_percent");

                    b.Property<double>("AwayGoalsScoredAt46To60PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at46_to60_percent_at_away");

                    b.Property<int>("AwayGoalsScoredAt61To75")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at61_to75");

                    b.Property<int>("AwayGoalsScoredAt61To75AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at61_to75_at_away");

                    b.Property<double>("AwayGoalsScoredAt61To75Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at61_to75_percent");

                    b.Property<double>("AwayGoalsScoredAt61To75PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at61_to75_percent_at_away");

                    b.Property<int>("AwayGoalsScoredAt76To90")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at76_to90");

                    b.Property<int>("AwayGoalsScoredAt76To90AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at76_to90_at_away");

                    b.Property<double>("AwayGoalsScoredAt76To90Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at76_to90_percent");

                    b.Property<double>("AwayGoalsScoredAt76To90PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at76_to90_percent_at_away");

                    b.Property<int>("AwayGoalsScoredFTTotal")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_f_t_total");

                    b.Property<int>("AwayGoalsScoredFTTotalAtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_f_t_total_at_away");

                    b.Property<int>("AwayGoalsScoredHTTotal")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_h_t_total");

                    b.Property<int>("AwayGoalsScoredHTTotalAtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_h_t_total_at_away");

                    b.Property<int>("AwayGoalsScoredTotal")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_total");

                    b.Property<int>("AwayGoalsScoredTotalAtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_total_at_away");

                    b.Property<double>("AwayLossesPercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_losses_percent_f_t_total");

                    b.Property<double>("AwayLossesPercentFTTotalAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_losses_percent_f_t_total_at_away");

                    b.Property<double>("AwayLossesPercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_losses_percent_h_t_total");

                    b.Property<double>("AwayLossesPercentHTTotalAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_losses_percent_h_t_total_at_away");

                    b.Property<double>("AwayPPGTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_p_p_g_total");

                    b.Property<double>("AwayPPGTotalAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_p_p_g_total_at_away");

                    b.Property<double>("AwayWinsPercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_wins_percent_f_t_total");

                    b.Property<double>("AwayWinsPercentFTTotalAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_wins_percent_f_t_total_at_away");

                    b.Property<double>("AwayWinsPercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_wins_percent_h_t_total");

                    b.Property<double>("AwayWinsPercentHTTotalAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_wins_percent_h_t_total_at_away");

                    b.Property<double>("AwayWinsPercentTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_wins_percent_total");

                    b.Property<double>("AwayWinsPercentTotalAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_wins_percent_total_at_away");

                    b.Property<int>("AwayWinsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("away_wins_total");

                    b.Property<int>("AwayWinsTotalAtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_wins_total_at_away");

                    b.Property<int>("FixtureCode")
                        .HasColumnType("integer")
                        .HasColumnName("fixture_code");

                    b.Property<double>("HomeAverageGoalsConcededFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_average_goals_conceded_f_t_total");

                    b.Property<double>("HomeAverageGoalsConcededFTTotalAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_average_goals_conceded_f_t_total_at_home");

                    b.Property<double>("HomeAverageGoalsConcededHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_average_goals_conceded_h_t_total");

                    b.Property<double>("HomeAverageGoalsConcededHTTotalAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_average_goals_conceded_h_t_total_at_home");

                    b.Property<double>("HomeAverageGoalsConcededTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_average_goals_conceded_total");

                    b.Property<double>("HomeAverageGoalsConcededTotalAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_average_goals_conceded_total_at_home");

                    b.Property<double>("HomeAverageGoalsScoredFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_average_goals_scored_f_t_total");

                    b.Property<double>("HomeAverageGoalsScoredFTTotalAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_average_goals_scored_f_t_total_at_home");

                    b.Property<double>("HomeAverageGoalsScoredHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_average_goals_scored_h_t_total");

                    b.Property<double>("HomeAverageGoalsScoredHTTotalAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_average_goals_scored_h_t_total_at_home");

                    b.Property<double>("HomeAverageGoalsScoredTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_average_goals_scored_total");

                    b.Property<double>("HomeAverageGoalsScoredTotalAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_average_goals_scored_total_at_home");

                    b.Property<double>("HomeBothToScorePercentTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_both_to_score_percent_total");

                    b.Property<double>("HomeBothToScorePercentTotalAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_both_to_score_percent_total_at_home");

                    b.Property<double>("HomeDrawsPercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_draws_percent_f_t_total");

                    b.Property<double>("HomeDrawsPercentFTTotalAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_draws_percent_f_t_total_at_home");

                    b.Property<double>("HomeDrawsPercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_draws_percent_h_t_total");

                    b.Property<double>("HomeDrawsPercentHTTotalAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_draws_percent_h_t_total_at_home");

                    b.Property<double>("HomeFailedToScorePercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_failed_to_score_percent_f_t_total");

                    b.Property<double>("HomeFailedToScorePercentFTTotalAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_failed_to_score_percent_f_t_total_at_home");

                    b.Property<double>("HomeFailedToScorePercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_failed_to_score_percent_h_t_total");

                    b.Property<double>("HomeFailedToScorePercentHTTotalAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_failed_to_score_percent_h_t_total_at_home");

                    b.Property<double>("HomeFailedToScorePercentTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_failed_to_score_percent_total");

                    b.Property<double>("HomeFailedToScorePercentTotalAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_failed_to_score_percent_total_at_home");

                    b.Property<double>("HomeFirstToScorePercentTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_first_to_score_percent_total");

                    b.Property<double>("HomeFirstToScorePercentTotalAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_first_to_score_percent_total_at_home");

                    b.Property<double>("HomeFixturesWithoutConcededGoalsPercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_fixtures_without_conceded_goals_percent_f_t_total");

                    b.Property<double>("HomeFixturesWithoutConcededGoalsPercentFTTotalAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_fixtures_without_conceded_goals_percent_f_t_total_at_home");

                    b.Property<double>("HomeFixturesWithoutConcededGoalsPercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_fixtures_without_conceded_goals_percent_h_t_total");

                    b.Property<double>("HomeFixturesWithoutConcededGoalsPercentHTTotalAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_fixtures_without_conceded_goals_percent_h_t_total_at_home");

                    b.Property<double>("HomeFixturesWithoutConcededGoalsPercentTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_fixtures_without_conceded_goals_percent_total");

                    b.Property<double>("HomeFixturesWithoutConcededGoalsPercentTotalAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_fixtures_without_conceded_goals_percent_total_at_home");

                    b.Property<int>("HomeGoalsConcededAt00To15")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at00_to15");

                    b.Property<int>("HomeGoalsConcededAt00To15AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at00_to15_at_home");

                    b.Property<double>("HomeGoalsConcededAt00To15Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at00_to15_percent");

                    b.Property<double>("HomeGoalsConcededAt00To15PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at00_to15_percent_at_home");

                    b.Property<int>("HomeGoalsConcededAt16To30")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at16_to30");

                    b.Property<int>("HomeGoalsConcededAt16To30AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at16_to30_at_home");

                    b.Property<double>("HomeGoalsConcededAt16To30Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at16_to30_percent");

                    b.Property<double>("HomeGoalsConcededAt16To30PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at16_to30_percent_at_home");

                    b.Property<int>("HomeGoalsConcededAt31To45")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at31_to45");

                    b.Property<int>("HomeGoalsConcededAt31To45AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at31_to45_at_home");

                    b.Property<double>("HomeGoalsConcededAt31To45Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at31_to45_percent");

                    b.Property<double>("HomeGoalsConcededAt31To45PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at31_to45_percent_at_home");

                    b.Property<int>("HomeGoalsConcededAt46To60")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at46_to60");

                    b.Property<int>("HomeGoalsConcededAt46To60AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at46_to60_at_home");

                    b.Property<double>("HomeGoalsConcededAt46To60Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at46_to60_percent");

                    b.Property<double>("HomeGoalsConcededAt46To60PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at46_to60_percent_at_home");

                    b.Property<int>("HomeGoalsConcededAt61To75")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at61_to75");

                    b.Property<int>("HomeGoalsConcededAt61To75AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at61_to75_at_home");

                    b.Property<double>("HomeGoalsConcededAt61To75Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at61_to75_percent");

                    b.Property<double>("HomeGoalsConcededAt61To75PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at61_to75_percent_at_home");

                    b.Property<int>("HomeGoalsConcededAt76To90")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at76_to90");

                    b.Property<int>("HomeGoalsConcededAt76To90AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at76_to90_at_home");

                    b.Property<double>("HomeGoalsConcededAt76To90Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at76_to90_percent");

                    b.Property<double>("HomeGoalsConcededAt76To90PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at76_to90_percent_at_home");

                    b.Property<int>("HomeGoalsConcededFTTotal")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_f_t_total");

                    b.Property<int>("HomeGoalsConcededFTTotalAtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_f_t_total_at_home");

                    b.Property<int>("HomeGoalsConcededHTTotal")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_h_t_total");

                    b.Property<int>("HomeGoalsConcededHTTotalAtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_h_t_total_at_home");

                    b.Property<int>("HomeGoalsConcededTotal")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_total");

                    b.Property<int>("HomeGoalsConcededTotalAtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_total_at_home");

                    b.Property<int>("HomeGoalsScoredAt00To15")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at00_to15");

                    b.Property<int>("HomeGoalsScoredAt00To15AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at00_to15_at_home");

                    b.Property<double>("HomeGoalsScoredAt00To15Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at00_to15_percent");

                    b.Property<double>("HomeGoalsScoredAt00To15PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at00_to15_percent_at_home");

                    b.Property<int>("HomeGoalsScoredAt16To30")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at16_to30");

                    b.Property<int>("HomeGoalsScoredAt16To30AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at16_to30_at_home");

                    b.Property<double>("HomeGoalsScoredAt16To30Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at16_to30_percent");

                    b.Property<double>("HomeGoalsScoredAt16To30PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at16_to30_percent_at_home");

                    b.Property<int>("HomeGoalsScoredAt31To45")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at31_to45");

                    b.Property<int>("HomeGoalsScoredAt31To45AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at31_to45_at_home");

                    b.Property<double>("HomeGoalsScoredAt31To45Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at31_to45_percent");

                    b.Property<double>("HomeGoalsScoredAt31To45PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at31_to45_percent_at_home");

                    b.Property<int>("HomeGoalsScoredAt46To60")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at46_to60");

                    b.Property<int>("HomeGoalsScoredAt46To60AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at46_to60_at_home");

                    b.Property<double>("HomeGoalsScoredAt46To60Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at46_to60_percent");

                    b.Property<double>("HomeGoalsScoredAt46To60PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at46_to60_percent_at_home");

                    b.Property<int>("HomeGoalsScoredAt61To75")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at61_to75");

                    b.Property<int>("HomeGoalsScoredAt61To75AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at61_to75_at_home");

                    b.Property<double>("HomeGoalsScoredAt61To75Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at61_to75_percent");

                    b.Property<double>("HomeGoalsScoredAt61To75PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at61_to75_percent_at_home");

                    b.Property<int>("HomeGoalsScoredAt76To90")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at76_to90");

                    b.Property<int>("HomeGoalsScoredAt76To90AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at76_to90_at_home");

                    b.Property<double>("HomeGoalsScoredAt76To90Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at76_to90_percent");

                    b.Property<double>("HomeGoalsScoredAt76To90PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at76_to90_percent_at_home");

                    b.Property<int>("HomeGoalsScoredFTTotal")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_f_t_total");

                    b.Property<int>("HomeGoalsScoredFTTotalAtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_f_t_total_at_home");

                    b.Property<int>("HomeGoalsScoredHTTotal")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_h_t_total");

                    b.Property<int>("HomeGoalsScoredHTTotalAtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_h_t_total_at_home");

                    b.Property<int>("HomeGoalsScoredTotal")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_total");

                    b.Property<int>("HomeGoalsScoredTotalAtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_total_at_home");

                    b.Property<double>("HomeLossesPercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_losses_percent_f_t_total");

                    b.Property<double>("HomeLossesPercentFTTotalAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_losses_percent_f_t_total_at_home");

                    b.Property<double>("HomeLossesPercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_losses_percent_h_t_total");

                    b.Property<double>("HomeLossesPercentHTTotalAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_losses_percent_h_t_total_at_home");

                    b.Property<double>("HomePPGTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_p_p_g_total");

                    b.Property<double>("HomePPGTotalAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_p_p_g_total_at_home");

                    b.Property<double>("HomeWinsPercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_wins_percent_f_t_total");

                    b.Property<double>("HomeWinsPercentFTTotalAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_wins_percent_f_t_total_at_home");

                    b.Property<double>("HomeWinsPercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_wins_percent_h_t_total");

                    b.Property<double>("HomeWinsPercentHTTotalAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_wins_percent_h_t_total_at_home");

                    b.Property<double>("HomeWinsPercentTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_wins_percent_total");

                    b.Property<double>("HomeWinsPercentTotalAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_wins_percent_total_at_home");

                    b.Property<int>("HomeWinsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("home_wins_total");

                    b.Property<int>("HomeWinsTotalAtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_wins_total_at_home");

                    b.HasKey("Code")
                        .HasName("p_k_fixture_stats_trade");

                    b.HasIndex("FixtureCode");

                    b.ToTable("fixture_stats_trade");
                });

            modelBuilder.Entity("BetPlacer.Fixtures.API.Models.Entities.FixtureGoalsModel", b =>
                {
                    b.HasOne("BetPlacer.Fixtures.API.Models.Entities.FixtureModel", "Fixture")
                        .WithMany()
                        .HasForeignKey("FixtureCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_fixture_goals__fixtures_fixture_code");

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("BetPlacer.Fixtures.API.Models.Entities.Trade.FixtureStatsTradeModel", b =>
                {
                    b.HasOne("BetPlacer.Fixtures.API.Models.Entities.FixtureModel", "Fixture")
                        .WithMany()
                        .HasForeignKey("FixtureCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_fixture_stats_trade_fixtures_fixture_code");

                    b.Navigation("Fixture");
                });
#pragma warning restore 612, 618
        }
    }
}
