// <auto-generated />
using System;
using BetPlacer.Fixtures.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BetPlacer.Fixtures.API.Migrations
{
    [DbContext(typeof(FixturesDbContext))]
    partial class FixturesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BetPlacer.Fixtures.API.Models.Entities.FixtureGoalsModel", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<int>("FixtureCode")
                        .HasColumnType("integer")
                        .HasColumnName("fixture_code");

                    b.Property<string>("Minute")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("minute");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Code")
                        .HasName("p_k_fixture_goals");

                    b.HasIndex("FixtureCode");

                    b.ToTable("fixture_goals");
                });

            modelBuilder.Entity("BetPlacer.Fixtures.API.Models.Entities.FixtureModel", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<int>("AwayTeamGoals")
                        .HasColumnType("integer")
                        .HasColumnName("away_team_goals");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("away_team_id");

                    b.Property<string>("AwayTeamImage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("away_team_image");

                    b.Property<string>("AwayTeamName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("away_team_name");

                    b.Property<double>("AwayTeamPPG")
                        .HasColumnType("double precision")
                        .HasColumnName("away_team_p_p_g");

                    b.Property<double>("AwayTeamXG")
                        .HasColumnType("double precision")
                        .HasColumnName("away_team_x_g");

                    b.Property<int>("HomeTeamGoals")
                        .HasColumnType("integer")
                        .HasColumnName("home_team_goals");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("home_team_id");

                    b.Property<string>("HomeTeamImage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("home_team_image");

                    b.Property<string>("HomeTeamName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("home_team_name");

                    b.Property<double>("HomeTeamPPG")
                        .HasColumnType("double precision")
                        .HasColumnName("home_team_p_p_g");

                    b.Property<double>("HomeTeamXG")
                        .HasColumnType("double precision")
                        .HasColumnName("home_team_x_g");

                    b.Property<int>("SeasonCode")
                        .HasColumnType("integer")
                        .HasColumnName("season_code");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Code")
                        .HasName("p_k_fixtures");

                    b.ToTable("fixtures");
                });

            modelBuilder.Entity("BetPlacer.Fixtures.API.Models.Entities.FixtureOdds", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<double>("AwayOdd")
                        .HasColumnType("double precision")
                        .HasColumnName("away_odd");

                    b.Property<double>("BTTSNoOdd")
                        .HasColumnType("double precision")
                        .HasColumnName("btts_no_odd");

                    b.Property<double>("BTTSYesOdd")
                        .HasColumnType("double precision")
                        .HasColumnName("btts_yes_odd");

                    b.Property<double>("DrawOdd")
                        .HasColumnType("double precision")
                        .HasColumnName("draw_odd");

                    b.Property<int>("FixtureCode")
                        .HasColumnType("integer")
                        .HasColumnName("fixture_code");

                    b.Property<double>("HomeOdd")
                        .HasColumnType("double precision")
                        .HasColumnName("home_odd");

                    b.Property<double>("Over25Odd")
                        .HasColumnType("double precision")
                        .HasColumnName("over25_odd");

                    b.Property<double>("Under25Odd")
                        .HasColumnType("double precision")
                        .HasColumnName("under25_odd");

                    b.HasKey("Code")
                        .HasName("p_k_fixture_odds");

                    b.ToTable("fixture_odds");
                });

            modelBuilder.Entity("BetPlacer.Fixtures.API.Models.Entities.Trade.FixtureStatsTradeModel", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<double>("AwayAverageGoalsConcededAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_average_goals_conceded_at_away");

                    b.Property<double>("AwayAverageGoalsConcededFTAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_avg_goals_conceded_ft_at_away");

                    b.Property<double>("AwayAverageGoalsConcededFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_average_goals_conceded_ft_total");

                    b.Property<double>("AwayAverageGoalsConcededHTAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_avg_goals_conceded_ht_at_away");

                    b.Property<double>("AwayAverageGoalsConcededHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_average_goals_conceded_ht_total");

                    b.Property<double>("AwayAverageGoalsConcededTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_average_goals_conceded_total");

                    b.Property<double>("AwayAverageGoalsScoredAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_average_goals_scored_at_away");

                    b.Property<double>("AwayAverageGoalsScoredFTAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_avg_goals_scored_ft_at_away");

                    b.Property<double>("AwayAverageGoalsScoredFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_avg_goals_scored_ft_total");

                    b.Property<double>("AwayAverageGoalsScoredHTAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_avg_goals_scored_ht_at_away");

                    b.Property<double>("AwayAverageGoalsScoredHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_avg_goals_scored_ht_total");

                    b.Property<double>("AwayAverageGoalsScoredTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_average_goals_scored_total");

                    b.Property<double>("AwayBothToScorePercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_both_to_score_percent_at_away");

                    b.Property<double>("AwayBothToScorePercentFTAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_both_to_score_percent_ft_at_away");

                    b.Property<double>("AwayBothToScorePercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_both_to_score_percent_ft_total");

                    b.Property<double>("AwayBothToScorePercentHTAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_both_to_score_percent_ht_at_away");

                    b.Property<double>("AwayBothToScorePercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_both_to_score_percent_ht_total");

                    b.Property<double>("AwayBothToScorePercentTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_both_to_score_percent_total");

                    b.Property<double>("AwayCleanSheetsPercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_clean_sheets_percent_at_away");

                    b.Property<double>("AwayCleanSheetsPercentFTAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_clean_sheets_percent_ft_at_away");

                    b.Property<double>("AwayCleanSheetsPercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_clean_sheets_percent_ft_total");

                    b.Property<double>("AwayCleanSheetsPercentHTAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_clean_sheets_percent_ht_at_away");

                    b.Property<double>("AwayCleanSheetsPercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_clean_sheets_percent_ht_total");

                    b.Property<double>("AwayCleanSheetsPercentTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_clean_sheets_percent_total");

                    b.Property<double>("AwayDrawsPercentFTAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_draws_percent_ft_at_away");

                    b.Property<double>("AwayDrawsPercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_draws_percent_ft_total");

                    b.Property<double>("AwayDrawsPercentHTAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_draws_percent_ht_at_away");

                    b.Property<double>("AwayDrawsPercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_draws_percent_ht_total");

                    b.Property<double>("AwayFailedToScorePercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_failed_to_score_percent_at_away");

                    b.Property<double>("AwayFailedToScorePercentFTAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_failed_to_score_percent_ft_at_away");

                    b.Property<double>("AwayFailedToScorePercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_failed_to_score_percent_ft_total");

                    b.Property<double>("AwayFailedToScorePercentHTAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_failed_to_score_percent_ht_at_away");

                    b.Property<double>("AwayFailedToScorePercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_failed_to_score_percent_ht_total");

                    b.Property<double>("AwayFailedToScorePercentTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_failed_to_score_percent_total");

                    b.Property<double>("AwayFirstToScorePercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_first_to_score_percent_at_away");

                    b.Property<double>("AwayFirstToScorePercentFTAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_first_to_score_percent_ft_at_away");

                    b.Property<double>("AwayFirstToScorePercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_first_to_score_percent_ft_total");

                    b.Property<double>("AwayFirstToScorePercentHTAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_first_to_score_percent_ht_at_away");

                    b.Property<double>("AwayFirstToScorePercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_first_to_score_percent_ht_total");

                    b.Property<double>("AwayFirstToScorePercentTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_first_to_score_percent_total");

                    b.Property<int>("AwayGoalsConcededAt0To15")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at_0_to_15");

                    b.Property<int>("AwayGoalsConcededAt0To15AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at_0_to_15_at_away");

                    b.Property<double>("AwayGoalsConcededAt0To15Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at_0_to_15_percent");

                    b.Property<double>("AwayGoalsConcededAt0To15PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at_0_to_15_percent_at_away");

                    b.Property<int>("AwayGoalsConcededAt16To30")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at_16_to_30");

                    b.Property<int>("AwayGoalsConcededAt16To30AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at_15_to_30_at_away");

                    b.Property<double>("AwayGoalsConcededAt16To30Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at_16_to_30_percent");

                    b.Property<double>("AwayGoalsConcededAt16To30PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at_15_to_30_percent_at_away");

                    b.Property<int>("AwayGoalsConcededAt31To45")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at_31_to_45");

                    b.Property<int>("AwayGoalsConcededAt31To45AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at_31_to_45_at_away");

                    b.Property<double>("AwayGoalsConcededAt31To45Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at_31_to_45_percent");

                    b.Property<double>("AwayGoalsConcededAt31To45PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at_31_to_45_percent_at_away");

                    b.Property<int>("AwayGoalsConcededAt46To60")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at_46_to_60");

                    b.Property<int>("AwayGoalsConcededAt46To60AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at_46_to_60_at_away");

                    b.Property<double>("AwayGoalsConcededAt46To60Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at_46_to_60_percent");

                    b.Property<double>("AwayGoalsConcededAt46To60PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at_46_to_60_percent_at_away");

                    b.Property<int>("AwayGoalsConcededAt61To75")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at_61_to_75");

                    b.Property<int>("AwayGoalsConcededAt61To75AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at_61_to_75_at_away");

                    b.Property<double>("AwayGoalsConcededAt61To75Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at_61_to_75_percent");

                    b.Property<double>("AwayGoalsConcededAt61To75PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at_61_to_75_percent_at_away");

                    b.Property<int>("AwayGoalsConcededAt76To90")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at_75_to_90");

                    b.Property<int>("AwayGoalsConcededAt76To90AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at_76_to_90_at_away");

                    b.Property<double>("AwayGoalsConcededAt76To90Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at_75_to_90_percent");

                    b.Property<double>("AwayGoalsConcededAt76To90PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_conceded_at_76_to_90_percent_at_away");

                    b.Property<int>("AwayGoalsConcededAtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_at_away");

                    b.Property<int>("AwayGoalsConcededFTAtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_ft_at_away");

                    b.Property<int>("AwayGoalsConcededFTTotal")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_ft_total");

                    b.Property<int>("AwayGoalsConcededHTAtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_ht_at_away");

                    b.Property<int>("AwayGoalsConcededHTTotal")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_ht_total");

                    b.Property<int>("AwayGoalsConcededTotal")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_conceded_total");

                    b.Property<int>("AwayGoalsScoredAt0To15")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at_0_to_15");

                    b.Property<int>("AwayGoalsScoredAt0To15AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at_0_to_15_at_away");

                    b.Property<double>("AwayGoalsScoredAt0To15Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at_0_to_15_percent");

                    b.Property<double>("AwayGoalsScoredAt0To15PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at_0_to_15_percent_at_away");

                    b.Property<int>("AwayGoalsScoredAt16To30")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at_16_to_30");

                    b.Property<int>("AwayGoalsScoredAt16To30AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at_15_to_30_at_away");

                    b.Property<double>("AwayGoalsScoredAt16To30Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at_16_to_30_percent");

                    b.Property<double>("AwayGoalsScoredAt16To30PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at_15_to_30_percent_at_away");

                    b.Property<int>("AwayGoalsScoredAt31To45")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at_31_to_45");

                    b.Property<int>("AwayGoalsScoredAt31To45AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at_31_to_45_at_away");

                    b.Property<double>("AwayGoalsScoredAt31To45Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at_31_to_45_percent");

                    b.Property<double>("AwayGoalsScoredAt31To45PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at_31_to_45_percent_at_away");

                    b.Property<int>("AwayGoalsScoredAt46To60")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at_46_to_60");

                    b.Property<int>("AwayGoalsScoredAt46To60AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at_46_to_60_at_away");

                    b.Property<double>("AwayGoalsScoredAt46To60Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at_46_to_60_percent");

                    b.Property<double>("AwayGoalsScoredAt46To60PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at_46_to_60_percent_at_away");

                    b.Property<int>("AwayGoalsScoredAt61To75")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at_61_to_75");

                    b.Property<int>("AwayGoalsScoredAt61To75AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at_61_to_75_at_away");

                    b.Property<double>("AwayGoalsScoredAt61To75Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at_61_to_75_percent");

                    b.Property<double>("AwayGoalsScoredAt61To75PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at_61_to_75_percent_at_away");

                    b.Property<int>("AwayGoalsScoredAt76To90")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at_75_to_90");

                    b.Property<int>("AwayGoalsScoredAt76To90AtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at_76_to_90_at_away");

                    b.Property<double>("AwayGoalsScoredAt76To90Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at_75_to_90_percent");

                    b.Property<double>("AwayGoalsScoredAt76To90PercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_goals_scored_at_76_to_90_percent_at_away");

                    b.Property<int>("AwayGoalsScoredAtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_at_away");

                    b.Property<int>("AwayGoalsScoredFTAtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_ft_at_away");

                    b.Property<int>("AwayGoalsScoredFTTotal")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_ft_total");

                    b.Property<int>("AwayGoalsScoredHTAtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_ht_at_away");

                    b.Property<int>("AwayGoalsScoredHTTotal")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_ht_total");

                    b.Property<int>("AwayGoalsScoredTotal")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals_scored_total");

                    b.Property<double>("AwayLossesPercentFTAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_losses_percent_ft_at_away");

                    b.Property<double>("AwayLossesPercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_losses_percent_ft_total");

                    b.Property<double>("AwayLossesPercentHTAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_losses_percent_ht_at_away");

                    b.Property<double>("AwayLossesPercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_losses_percent_ht_total");

                    b.Property<int>("AwayMatchesCountAtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_matches_count_at_away");

                    b.Property<int>("AwayMatchesCountOverall")
                        .HasColumnType("integer")
                        .HasColumnName("away_matches_count_overall");

                    b.Property<double>("AwayPPGAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_ppg_at_away");

                    b.Property<double>("AwayPPGTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_ppg_total");

                    b.Property<double>("AwayToScoreTwoZeroPercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_to_score_two_zero_percent_at_away");

                    b.Property<double>("AwayToScoreTwoZeroPercentFTAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_to_score_two_zero_percent_ft_at_away");

                    b.Property<double>("AwayToScoreTwoZeroPercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_to_score_two_zero_percent_ft_total");

                    b.Property<double>("AwayToScoreTwoZeroPercentHTAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_to_score_two_zero_percent_ht_at_away");

                    b.Property<double>("AwayToScoreTwoZeroPercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_to_score_two_zero_percent_ht_total");

                    b.Property<double>("AwayToScoreTwoZeroPercentTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_to_score_two_zero_percent_total");

                    b.Property<int>("AwayWinsAtAway")
                        .HasColumnType("integer")
                        .HasColumnName("away_wins_at_away");

                    b.Property<double>("AwayWinsPercentAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_wins_percent_at_away");

                    b.Property<double>("AwayWinsPercentFTAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_wins_percent_ft_at_away");

                    b.Property<double>("AwayWinsPercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_wins_percent_ft_total");

                    b.Property<double>("AwayWinsPercentHTAtAway")
                        .HasColumnType("double precision")
                        .HasColumnName("away_wins_percent_ht_at_away");

                    b.Property<double>("AwayWinsPercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_wins_percent_ht_total");

                    b.Property<double>("AwayWinsPercentTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("away_wins_percent_total");

                    b.Property<int>("AwayWinsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("away_wins_total");

                    b.Property<int>("FixtureCode")
                        .HasColumnType("integer")
                        .HasColumnName("fixture_code");

                    b.Property<double>("HomeAverageGoalsConcededAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_average_goals_conceded_at_home");

                    b.Property<double>("HomeAverageGoalsConcededFTAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_avg_goals_conceded_ft_at_home");

                    b.Property<double>("HomeAverageGoalsConcededFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_average_goals_conceded_ft_total");

                    b.Property<double>("HomeAverageGoalsConcededHTAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_avg_goals_conceded_ht_at_home");

                    b.Property<double>("HomeAverageGoalsConcededHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_average_goals_conceded_ht_total");

                    b.Property<double>("HomeAverageGoalsConcededTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_average_goals_conceded_total");

                    b.Property<double>("HomeAverageGoalsScoredAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_average_goals_scored_at_home");

                    b.Property<double>("HomeAverageGoalsScoredFTAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_avg_goals_scored_ft_at_home");

                    b.Property<double>("HomeAverageGoalsScoredFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_avg_goals_scored_ft_total");

                    b.Property<double>("HomeAverageGoalsScoredHTAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_avg_goals_scored_ht_at_home");

                    b.Property<double>("HomeAverageGoalsScoredHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_avg_goals_scored_ht_total");

                    b.Property<double>("HomeAverageGoalsScoredTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_average_goals_scored_total");

                    b.Property<double>("HomeBothToScorePercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_both_to_score_percent_at_home");

                    b.Property<double>("HomeBothToScorePercentFTAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_both_to_score_percent_ft_at_home");

                    b.Property<double>("HomeBothToScorePercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_both_to_score_percent_ft_total");

                    b.Property<double>("HomeBothToScorePercentHTAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_both_to_score_percent_ht_at_home");

                    b.Property<double>("HomeBothToScorePercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_both_to_score_percent_ht_total");

                    b.Property<double>("HomeBothToScorePercentTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_both_to_score_percent_total");

                    b.Property<double>("HomeCleanSheetsPercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_clean_sheets_percent_at_home");

                    b.Property<double>("HomeCleanSheetsPercentFTAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_clean_sheets_percent_ft_at_home");

                    b.Property<double>("HomeCleanSheetsPercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_clean_sheets_percent_ft_total");

                    b.Property<double>("HomeCleanSheetsPercentHTAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_clean_sheets_percent_ht_at_home");

                    b.Property<double>("HomeCleanSheetsPercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_clean_sheets_percent_ht_total");

                    b.Property<double>("HomeCleanSheetsPercentTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_clean_sheets_percent_total");

                    b.Property<double>("HomeDrawsPercentFTAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_draws_percent_ft_at_home");

                    b.Property<double>("HomeDrawsPercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_draws_percent_ft_total");

                    b.Property<double>("HomeDrawsPercentHTAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_draws_percent_ht_at_home");

                    b.Property<double>("HomeDrawsPercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_draws_percent_ht_total");

                    b.Property<double>("HomeFailedToScorePercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_failed_to_score_percent_at_home");

                    b.Property<double>("HomeFailedToScorePercentFTAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_failed_to_score_percent_ft_at_home");

                    b.Property<double>("HomeFailedToScorePercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_failed_to_score_percent_ft_total");

                    b.Property<double>("HomeFailedToScorePercentHTAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_failed_to_score_percent_ht_at_home");

                    b.Property<double>("HomeFailedToScorePercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_failed_to_score_percent_ht_total");

                    b.Property<double>("HomeFailedToScorePercentTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_failed_to_score_percent_total");

                    b.Property<double>("HomeFirstToScorePercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_first_to_score_percent_at_home");

                    b.Property<double>("HomeFirstToScorePercentFTAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_first_to_score_percent_ft_at_home");

                    b.Property<double>("HomeFirstToScorePercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_first_to_score_percent_ft_total");

                    b.Property<double>("HomeFirstToScorePercentHTAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_first_to_score_percent_ht_at_home");

                    b.Property<double>("HomeFirstToScorePercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_first_to_score_percent_ht_total");

                    b.Property<double>("HomeFirstToScorePercentTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_first_to_score_percent_total");

                    b.Property<int>("HomeGoalsConcededAt0To15")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at_0_to_15");

                    b.Property<int>("HomeGoalsConcededAt0To15AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at_0_to_15_at_home");

                    b.Property<double>("HomeGoalsConcededAt0To15Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at_0_to_15_percent");

                    b.Property<double>("HomeGoalsConcededAt0To15PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at_0_to_15_percent_at_home");

                    b.Property<int>("HomeGoalsConcededAt16To30")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at_16_to_30");

                    b.Property<int>("HomeGoalsConcededAt16To30AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at_15_to_30_at_home");

                    b.Property<double>("HomeGoalsConcededAt16To30Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at_16_to_30_percent");

                    b.Property<double>("HomeGoalsConcededAt16To30PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at_15_to_30_percent_at_home");

                    b.Property<int>("HomeGoalsConcededAt31To45")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at_31_to_45");

                    b.Property<int>("HomeGoalsConcededAt31To45AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at_31_to_45_at_home");

                    b.Property<double>("HomeGoalsConcededAt31To45Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at_31_to_45_percent");

                    b.Property<double>("HomeGoalsConcededAt31To45PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at_31_to_45_percent_at_home");

                    b.Property<int>("HomeGoalsConcededAt46To60")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at_46_to_60");

                    b.Property<int>("HomeGoalsConcededAt46To60AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at_46_to_60_at_home");

                    b.Property<double>("HomeGoalsConcededAt46To60Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at_46_to_60_percent");

                    b.Property<double>("HomeGoalsConcededAt46To60PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at_46_to_60_percent_at_home");

                    b.Property<int>("HomeGoalsConcededAt61To75")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at_61_to_75");

                    b.Property<int>("HomeGoalsConcededAt61To75AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at_61_to_75_at_home");

                    b.Property<double>("HomeGoalsConcededAt61To75Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at_61_to_75_percent");

                    b.Property<double>("HomeGoalsConcededAt61To75PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at_61_to_75_percent_at_home");

                    b.Property<int>("HomeGoalsConcededAt76To90")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at_75_to_90");

                    b.Property<int>("HomeGoalsConcededAt76To90AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at_76_to_90_at_home");

                    b.Property<double>("HomeGoalsConcededAt76To90Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at_75_to_90_percent");

                    b.Property<double>("HomeGoalsConcededAt76To90PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_conceded_at_76_to_90_percent_at_home");

                    b.Property<int>("HomeGoalsConcededAtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_at_home");

                    b.Property<int>("HomeGoalsConcededFTAtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_ft_at_home");

                    b.Property<int>("HomeGoalsConcededFTTotal")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_ft_total");

                    b.Property<int>("HomeGoalsConcededHTAtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_ht_at_home");

                    b.Property<int>("HomeGoalsConcededHTTotal")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_ht_total");

                    b.Property<int>("HomeGoalsConcededTotal")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_conceded_total");

                    b.Property<int>("HomeGoalsScoredAt0To15")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at_0_to_15");

                    b.Property<int>("HomeGoalsScoredAt0To15AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at_0_to_15_at_home");

                    b.Property<double>("HomeGoalsScoredAt0To15Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at_0_to_15_percent");

                    b.Property<double>("HomeGoalsScoredAt0To15PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at_0_to_15_percent_at_home");

                    b.Property<int>("HomeGoalsScoredAt16To30")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at_16_to_30");

                    b.Property<int>("HomeGoalsScoredAt16To30AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at_15_to_30_at_home");

                    b.Property<double>("HomeGoalsScoredAt16To30Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at_16_to_30_percent");

                    b.Property<double>("HomeGoalsScoredAt16To30PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at_15_to_30_percent_at_home");

                    b.Property<int>("HomeGoalsScoredAt31To45")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at_31_to_45");

                    b.Property<int>("HomeGoalsScoredAt31To45AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at_31_to_45_at_home");

                    b.Property<double>("HomeGoalsScoredAt31To45Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at_31_to_45_percent");

                    b.Property<double>("HomeGoalsScoredAt31To45PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at_31_to_45_percent_at_home");

                    b.Property<int>("HomeGoalsScoredAt46To60")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at_46_to_60");

                    b.Property<int>("HomeGoalsScoredAt46To60AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at_46_to_60_at_home");

                    b.Property<double>("HomeGoalsScoredAt46To60Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at_46_to_60_percent");

                    b.Property<double>("HomeGoalsScoredAt46To60PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at_46_to_60_percent_at_home");

                    b.Property<int>("HomeGoalsScoredAt61To75")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at_61_to_75");

                    b.Property<int>("HomeGoalsScoredAt61To75AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at_61_to_75_at_home");

                    b.Property<double>("HomeGoalsScoredAt61To75Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at_61_to_75_percent");

                    b.Property<double>("HomeGoalsScoredAt61To75PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at_61_to_75_percent_at_home");

                    b.Property<int>("HomeGoalsScoredAt76To90")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at_75_to_90");

                    b.Property<int>("HomeGoalsScoredAt76To90AtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at_76_to_90_at_home");

                    b.Property<double>("HomeGoalsScoredAt76To90Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at_75_to_90_percent");

                    b.Property<double>("HomeGoalsScoredAt76To90PercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_goals_scored_at_76_to_90_percent_at_home");

                    b.Property<int>("HomeGoalsScoredAtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_at_home");

                    b.Property<int>("HomeGoalsScoredFTAtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_ft_at_home");

                    b.Property<int>("HomeGoalsScoredFTTotal")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_ft_total");

                    b.Property<int>("HomeGoalsScoredHTAtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_ht_at_home");

                    b.Property<int>("HomeGoalsScoredHTTotal")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_ht_total");

                    b.Property<int>("HomeGoalsScoredTotal")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals_scored_total");

                    b.Property<double>("HomeLossesPercentFTAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_losses_percent_ft_at_home");

                    b.Property<double>("HomeLossesPercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_losses_percent_ft_total");

                    b.Property<double>("HomeLossesPercentHTAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_losses_percent_ht_at_home");

                    b.Property<double>("HomeLossesPercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_losses_percent_ht_total");

                    b.Property<int>("HomeMatchesCountAtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_matches_count_at_home");

                    b.Property<int>("HomeMatchesCountOverall")
                        .HasColumnType("integer")
                        .HasColumnName("home_matches_count_overall");

                    b.Property<double>("HomePPGAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_ppg_at_home");

                    b.Property<double>("HomePPGTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_ppg_total");

                    b.Property<double>("HomeToScoreTwoZeroPercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_to_score_two_zero_percent_at_home");

                    b.Property<double>("HomeToScoreTwoZeroPercentFTAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_to_score_two_zero_percent_ft_at_home");

                    b.Property<double>("HomeToScoreTwoZeroPercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_to_score_two_zero_percent_ft_total");

                    b.Property<double>("HomeToScoreTwoZeroPercentHTAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_to_score_two_zero_percent_ht_at_home");

                    b.Property<double>("HomeToScoreTwoZeroPercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_to_score_two_zero_percent_ht_total");

                    b.Property<double>("HomeToScoreTwoZeroPercentTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_to_score_two_zero_percent_total");

                    b.Property<int>("HomeWinsAtHome")
                        .HasColumnType("integer")
                        .HasColumnName("home_wins_at_home");

                    b.Property<double>("HomeWinsPercentAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_wins_percent_at_home");

                    b.Property<double>("HomeWinsPercentFTAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_wins_percent_ft_at_home");

                    b.Property<double>("HomeWinsPercentFTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_wins_percent_ft_total");

                    b.Property<double>("HomeWinsPercentHTAtHome")
                        .HasColumnType("double precision")
                        .HasColumnName("home_wins_percent_ht_at_home");

                    b.Property<double>("HomeWinsPercentHTTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_wins_percent_ht_total");

                    b.Property<double>("HomeWinsPercentTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("home_wins_percent_total");

                    b.Property<int>("HomeWinsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("home_wins_total");

                    b.HasKey("Code")
                        .HasName("p_k_fixture_stats_trade");

                    b.HasIndex("FixtureCode");

                    b.ToTable("fixture_stats_trade");
                });

            modelBuilder.Entity("BetPlacer.Fixtures.API.Models.Entities.FixtureGoalsModel", b =>
                {
                    b.HasOne("BetPlacer.Fixtures.API.Models.Entities.FixtureModel", "Fixture")
                        .WithMany()
                        .HasForeignKey("FixtureCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_fixture_goals__fixtures_fixture_code");

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("BetPlacer.Fixtures.API.Models.Entities.Trade.FixtureStatsTradeModel", b =>
                {
                    b.HasOne("BetPlacer.Fixtures.API.Models.Entities.FixtureModel", "Fixture")
                        .WithMany()
                        .HasForeignKey("FixtureCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_fixture_stats_trade_fixtures_fixture_code");

                    b.Navigation("Fixture");
                });
#pragma warning restore 612, 618
        }
    }
}
